import React from 'react';
import { FormRenderer } from '../lib/molecules/FormRenderer';
import { FormDefinition } from '../lib/interfaces/form-interfaces';

// Example of a form with AI-generated summary containing template variables
const aiGeneratedFormExample: FormDefinition = {
  app: {
    title: 'Insurance Application',
    pages: [
      {
        id: 'personal-info',
        title: 'Personal Information',
        route: '/personal',
        components: [
          {
            type: 'input',
            id: 'fullName',
            label: 'Full Name',
            validation: { required: true },
            props: { placeholder: 'Enter your full name' },
          },
          {
            type: 'input',
            id: 'email',
            label: 'Email Address',
            validation: { required: true },
            props: {
              placeholder: 'Enter your email',
              inputType: 'email',
            },
          },
          {
            type: 'radio',
            id: 'smoker',
            label: 'Do you smoke?',
            validation: { required: true },
            options: [
              { label: 'Yes', value: 'yes' },
              { label: 'No', value: 'no' },
            ],
          },
          {
            type: 'checkbox',
            id: 'preExisting',
            label: 'Do you have any pre-existing medical conditions?',
          },
          {
            type: 'checkbox',
            id: 'takingMedication',
            label: 'Are you currently taking any medications?',
          },
        ],
        nextPage: 'confirmation',
      },
      {
        id: 'confirmation',
        title: 'Application Summary',
        route: '/confirmation',
        isConfirmationPage: true,
        isEndPage: true,
        components: [
          {
            type: 'confirmation',
            id: 'application-summary',
            label: 'Application Summary',
            props: {
              confirmationSettings: {
                showSummary: false, // Don't show the regular summary
                customTitle: 'Application Summary',
                customMessage: `Name
{{fullName}}

Email
{{email}}

Health Overview
Smoking: {{smoker}} • Pre-existing: {{preExisting}} • Medications: {{takingMedication}}

Please review the information above and click submit to complete your application.`,
              },
            },
          },
        ],
      },
    ],
    thankYouPage: {
      title: 'Application Submitted!',
      message:
        'Your insurance application has been submitted successfully. We will review it and get back to you within 2-3 business days.',
      showRestartButton: true,
    },
  },
};

export const AIGeneratedSummaryExample: React.FC = () => {
  const handleSubmit = (formValues: Record<string, unknown>) => {
    console.log('Form submitted with values:', formValues);
    alert('Application submitted successfully! Check the console for details.');
  };

  return (
    <div className="max-w-2xl mx-auto p-6">
      <div className="mb-6 p-4 bg-yellow-50 border border-yellow-200 rounded-md">
        <h3 className="text-lg font-medium text-yellow-800 mb-2">
          AI-Generated Summary Example
        </h3>
        <p className="text-yellow-700 text-sm">
          This form demonstrates how the confirmation component handles template
          variables like <code>{'{{fullName}}'}</code>,{' '}
          <code>{'{{email}}'}</code>, etc. that are often generated by AI when
          creating custom form summaries.
        </p>
      </div>

      <FormRenderer formJson={aiGeneratedFormExample} onSubmit={handleSubmit} />
    </div>
  );
};

export default AIGeneratedSummaryExample;
